### PR TITLE
Use read_str helper to copy NULL-terminalted syscall parameter buffers

### PR DESCRIPTION
**Pull request by pothos**
The existing bpf_probe_read call had a failure in one corner case where
    we didn't know the size of a NULL-terminated string and just copied as
    much as fitted into the argument store. This failed when we reached the
    end of a mapped memory area.
    Use the bpf_probe_read_str helper to only copy as much as needed.
    Later migrate to the other bpf_probe_read_user(_str) function because
    we operate on userspace memory but since this requires Linux 5.5 it
    is not done now.

### CODE REVIEW

**Comment by alban** [comment]
This requires Linux 5.5 according to https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md and so far traceloop supported 4.14 (there are some workarounds in the code to support 4.14). I wonder if we could support both 4.14 and 5.5 by switching the right function at runtime by detecting the version.

Some ideas:
- https://github.com/DataDog/gobpf/pull/1

**Comment by pothos** [comment]
Ok, then I'll change it to `probe_read_str`

**Comment by pothos** [comment]
Done

**Review by alban — APPROVED** [review]
LGTM

**Pull request merged**
